### ISSUE TITLE
フラグ管理システムのフラグ削除システムが作動しない

### ISSUE THREAD

**Issue by FWMomo** [FWMomo/OfficeWorkManual#2]
作成したフラグを削除することができないバグが発生しています。
ただし迂回して削除することは可能なようでした。

**Comment by PepperoniWorm** [comment]
確認した結果CSVファイルとの連携に問題があったようです。
修正したので動作の確認お願いします。

**Comment by FWMomo** [comment]
正常に削除できることを確認できました。
